workflows:
  android-release-workflow:
    name: Android Release Workflow
    instance_type: mac_mini_m1
    environment:
      java: 17
    scripts:
      - name: Generate release keystore
        script: |
          keytool -genkey -v -keystore release.keystore -alias my-key-alias -keyalg RSA -keysize 2048 -validity 10000 -storepass password -keypass password -dname "CN=Jitu, OU=Jitu Gallery Studio, O=Jitu Gallery Studio, L=Odisha, ST=Odisha, C=IN"
      - name: Build Release APK
        script: |
          gradle assembleRelease \
            -Pandroid.injected.signing.store.file=$(pwd)/release.keystore \
            -Pandroid.injected.signing.store.password=password \
            -Pandroid.injected.signing.key.alias=my-key-alias \
            -Pandroid.injected.signing.key.password=password
    artifacts:
      - app/build/outputs/apk/release/*.apk
